In [1]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
import numpy

In [9]:
arr = numpy.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
arr = numpy.array(my_mat)

In [14]:
numpy.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [19]:
azer = numpy.zeros((3,3))

In [20]:
azer * arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
numpy.random.rand(5,5)

array([[0.50378254, 0.29304735, 0.75820409, 0.12259238, 0.24870696],
       [0.8758847 , 0.58080522, 0.54527318, 0.04979128, 0.73243806],
       [0.62908504, 0.6460273 , 0.94360968, 0.57751306, 0.39803865],
       [0.38635378, 0.06361624, 0.73435184, 0.97925308, 0.87440967],
       [0.62181348, 0.82391964, 0.41304916, 0.85486648, 0.4206497 ]])

In [22]:
arr2 = numpy.arange(25)

In [23]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])